spring.ai.google.genai.api-key=<your-Gemini-key>
spring.ai.google.genai.chat.model=gemini-2.5-flash

!spring.ai.openai.api-key=<your-OpenAI-key>
!spring.ai.openai.chat.model=gpt-4o

spring.ai.mcp.client.stdio.connections.gateway.command=docker
spring.ai.mcp.client.stdio.connections.gateway.args=mcp,gateway,run,--profile,mcp_demo
