<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Spring AI' Course: The ChatClient in Depth</description>
    <name>the-chatclient-in-depth</name>

    <groupId>com.baeldung</groupId>
    <artifactId>lsai-the-chatclient-in-depth</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>prompts-roles-start</module>
        <module>prompts-roles-end</module>
        <module>ai-providers-start</module>
        <module>ai-providers-end</module>
        <module>streaming-responses-start</module>
        <module>streaming-responses-end</module>
        <module>structured-output-start</module>
        <module>structured-output-end</module>
    </modules>
</project>
