spring.ai.google.genai.api-key=<your-Gemini-key>
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.embedding.api-key=<your-Gemini-key>
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

!spring.ai.openai.api-key=<your-OpenAI-key>
!spring.ai.openai.chat.model=gpt-4o
