package com.baeldung.controllers;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ChatController {

    private final ChatClient chatClient;

    public ChatController(ChatClient.Builder builder) {
        this.chatClient = builder.build();
    }

    @GetMapping("/chat")
    public String chat(@RequestParam String message) {
        ChatResponse response = chatClient.prompt()
                .user(message)
                .options(ChatOptions.builder()
                        .temperature(0.9)
                        .build())
                // .options(OpenAiChatOptions.builder()
                //         .frequencyPenalty(0.5)
                //         .build())
                .call()
                .chatResponse();

        String model = response.getMetadata().getModel();
        System.out.println("Response generated by model: " + model);

        return response.getResult().getOutput().getText();
    }
}
