spring.ai.google.genai.api-key=<your-Gemini-key>
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

!spring.ai.openai.api-key=<your OpenAI API key>
!spring.ai.openai.chat.options.model=gpt-4o
