spring.ai.google.genai.api-key=<your-Gemini-key>
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.api-key=<your-Gemini-key>
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

!spring.ai.openai.api-key=<your-OpenAI-key>
!spring.ai.openai.chat.options.model=gpt-4o
